import type { Destination } from '@/types'
import { NAIRA_RATES, formatNaira } from './constants'

function naira(amount: number, currency: string) {
  return formatNaira(amount * (NAIRA_RATES[currency] || 1))
}

function nairaRange(min: number, max: number, currency: string) {
  return `${naira(min, currency)}–${naira(max, currency)}`
}

export const destinations: Record<string, Destination> = {
  canada: {
    slug: 'canada',
    name: 'Canada',
    flag: '🇨🇦',
    gradient: 'linear-gradient(135deg, #8B0000, #CC0000, #FF4444)',
    accent: '#CC0000',
    keyStat: 'Up to 3yr Post-Study Work',
    visaSuccess: '99%',
    tuition: { min: 13000, max: 30000, currency: 'CAD' },
    living: { min: 10000, max: 15000, currency: 'CAD' },
    workRights: '20hrs/wk + full-time on breaks',
    postStudy: 'Up to 3yr PGWP',
    visaProcessing: '8–12 weeks',
    community: 'Large — One of the largest Nigerian student populations outside Africa, concentrated in Ontario, Manitoba, and Saskatchewan. Strong Pentecostal church networks and cultural communities throughout.',
    communitySize: 'Large',
    prPathway: 'Yes',
    h1: 'Study in Canada from Nigeria',
    metaTitle: 'Study in Canada from Nigeria 2025 | The Study Abroad Consultant',
    metaDescription: 'Expert guidance for Nigerian students applying to Canada. 99% visa success rate. Full Naira cost breakdown. Free consultation.',
    whyChoose: [
      { icon: 'TrendingUp', title: 'PR Pathway', description: 'Canada offers one of the clearest permanent residency pathways for international students through Express Entry and PNP programs.' },
      { icon: 'DollarSign', title: 'Affordable vs UK/USA', description: 'Tuition ranges from ₦14.3M–₦33M/yr — significantly lower than the UK or USA for comparable quality.' },
      { icon: 'Briefcase', title: 'PGWP Flexibility', description: 'The Post-Graduation Work Permit allows up to 3 years of open work — no employer sponsorship needed.' },
      { icon: 'Users', title: 'Multicultural Society', description: 'Canada is one of the most diverse countries in the world, with a large and welcoming Nigerian diaspora.' },
      { icon: 'Building', title: 'Strong Job Market', description: 'High demand for skilled workers in tech, healthcare, business, and engineering across provinces.' },
      { icon: 'GraduationCap', title: 'In-Demand Programs', description: 'Nursing, IT, business analytics, and supply chain management programs with strong employment outcomes.' },
    ],
    communityFacts: [
      'Largest Nigerian student population in North America',
      'Active Nigerian student unions at most universities',
      'Strong Pentecostal church networks in every major city',
    ],
    timeline: [
      { week: 'Week 1', title: 'Initial Consultation', description: 'Free assessment of your profile, budget, and study goals for Canada.' },
      { week: 'Weeks 2–4', title: 'IELTS & Document Prep', description: 'IELTS preparation guidance and gathering of academic transcripts, WAEC results, and financial documents.' },
      { week: 'Weeks 4–6', title: 'University Shortlisting', description: 'We match you with 3–5 Canadian universities based on your GPA, budget, and career goals.' },
      { week: 'Weeks 6–10', title: 'Application Submission', description: 'Complete application packages submitted to your chosen universities. Processing typically takes 4–6 weeks.' },
      { week: 'Weeks 10–14', title: 'Offer Letter & Acceptance', description: 'Receive and compare offers. Accept your preferred university and pay tuition deposit.' },
      { week: 'Weeks 14–18', title: 'IRCC Visa Application', description: 'Complete study permit application with biometrics at the Lagos or Abuja visa centre.' },
      { week: 'Weeks 18–26', title: 'Visa Decision', description: 'Processing typically takes 8–12 weeks. We track your application and respond to any requests.' },
      { week: 'Weeks 26–28', title: 'Pre-Departure & Arrival', description: 'Accommodation, flight booking, and 3 months of post-arrival support in Canada.' },
    ],
    costTable: [
      { item: 'Minimum Tuition/yr', foreign: 'CAD 13,000', naira: naira(13000, 'CAD') },
      { item: 'Maximum Tuition/yr', foreign: 'CAD 30,000', naira: naira(30000, 'CAD') },
      { item: 'Living Expenses/yr', foreign: 'CAD 10,000–15,000', naira: nairaRange(10000, 15000, 'CAD') },
      { item: 'Health Insurance/yr', foreign: 'CAD 600–900', naira: nairaRange(600, 900, 'CAD') },
      { item: 'Total Estimated/yr', foreign: 'CAD 23,600–45,900', naira: nairaRange(23600, 45900, 'CAD') },
    ],
    healthInsurance: { foreign: 'CAD 600–900/yr', naira: nairaRange(600, 900, 'CAD') },
    quizQuestions: [
      { question: 'Are you interested in permanent residency after studies?', options: ['Definitely', 'Maybe', 'Not sure', 'No'] },
      { question: 'What is your annual budget (tuition + living)?', options: ['Under ₦25M', '₦25M–₦35M', '₦35M–₦50M', 'Over ₦50M'] },
      { question: 'What is your IELTS score (or expected)?', options: ['Below 6.0', '6.0–6.5', '6.5–7.0', '7.0+'] },
      { question: 'What program are you interested in?', options: ['Business/MBA', 'Engineering/IT', 'Health Sciences', 'Other'] },
      { question: 'When do you want to start?', options: ['January 2026', 'May 2026', 'September 2026', 'Later'] },
    ],
    faqs: [
      { question: 'What is the minimum IELTS score for Canada?', answer: 'Most Canadian universities require an overall IELTS score of 6.0–6.5, with no individual band below 6.0. Some pathway programs accept 5.5.' },
      { question: 'How does the PGWP work?', answer: 'The Post-Graduation Work Permit (PGWP) allows you to work in Canada for up to 3 years after graduation, depending on your program length. It does not require a job offer or employer sponsorship.' },
      { question: 'How much proof of funds do I need?', answer: 'You need to show at least CAD 10,000 (≈₦11M) plus your first year\'s tuition. Funds should be seasoned (in your account for 3–6 months). CBN documentation is required.' },
      { question: 'Do I need an NYSC certificate to apply?', answer: 'No — NYSC completion is not required for Canadian study permit applications. However, you may need an enrolment or exemption letter depending on your age and qualification.' },
      { question: 'How long does visa processing take in 2025?', answer: 'Canadian study permit processing from Nigeria currently takes 8–12 weeks. We recommend starting your application at least 4–5 months before your intended start date.' },
      { question: 'Can I bring my family to Canada on a study permit?', answer: 'Yes. Your spouse can apply for an open work permit, and dependent children can attend school. This applies if you are studying at a DLI in a program of 6+ months.' },
    ],
    relatedDestinations: ['uk', 'australia'],
  },

  uk: {
    slug: 'uk',
    name: 'United Kingdom',
    flag: '🇬🇧',
    gradient: 'linear-gradient(135deg, #012169, #C8102E, #8B0000)',
    accent: '#C8102E',
    keyStat: '2yr Graduate Visa',
    visaSuccess: '97%',
    tuition: { min: 10000, max: 38000, currency: 'GBP' },
    living: { min: 12000, max: 15000, currency: 'GBP' },
    workRights: '20hrs during term, full-time holidays',
    postStudy: '2yr Graduate Visa',
    visaProcessing: '~3 weeks',
    community: 'Large — Over 200,000 Nigerians in the UK, one of the largest diaspora communities in the world. Nigerian churches, restaurants, and student unions at virtually every major university.',
    communitySize: 'Large',
    prPathway: 'Limited',
    h1: 'Study in the UK from Nigeria: Costs in Naira, Visa & Universities (2025)',
    metaTitle: 'Study in the UK from Nigeria 2025 | The Study Abroad Consultant',
    metaDescription: 'Expert guidance for Nigerian students applying to UK universities. 97% visa success rate. Full Naira cost breakdown. Free consultation.',
    whyChoose: [
      { icon: 'Award', title: 'World-Class Universities', description: 'Home to 4 of the world\'s top 10 universities and dozens of globally ranked institutions.' },
      { icon: 'Clock', title: 'Shorter Programs', description: 'Complete a Master\'s in just 1 year — saving time and money compared to 2-year programs elsewhere.' },
      { icon: 'Briefcase', title: '2yr Graduate Visa', description: 'Work in any role for 2 years after graduation with no employer sponsorship required.' },
      { icon: 'GraduationCap', title: 'Global Recognition', description: 'UK degrees are recognized and respected by employers worldwide.' },
      { icon: 'Users', title: 'Nigerian Community', description: 'Over 200,000 Nigerians in the UK with established support networks at every major university.' },
      { icon: 'Globe', title: 'Cultural Experience', description: 'London, Manchester, Birmingham — vibrant multicultural cities with rich history and opportunities.' },
    ],
    communityFacts: [
      'Over 200,000 Nigerians living in the UK',
      'Nigerian student unions at virtually every major university',
      'Nigerian restaurants and churches in all major cities',
    ],
    timeline: [
      { week: 'Week 1', title: 'Initial Consultation', description: 'Free assessment of your profile and UK university options.' },
      { week: 'Weeks 2–3', title: 'University Shortlisting', description: 'Matched to 3–5 UK universities based on your grades, budget, and career goals.' },
      { week: 'Weeks 3–6', title: 'Application & Documents', description: 'Personal statement, references, and application submission via UCAS or directly.' },
      { week: 'Weeks 6–10', title: 'Offer & CAS Letter', description: 'Accept your offer, pay deposit, and receive your CAS (Confirmation of Acceptance for Studies).' },
      { week: 'Weeks 10–14', title: 'Visa Application', description: 'Financial evidence preparation (28-day rule), NHS surcharge payment, biometrics in Nigeria.' },
      { week: 'Weeks 14–17', title: 'Visa Decision', description: 'UK student visas from Nigeria typically take ~3 weeks from biometrics.' },
      { week: 'Weeks 17–20', title: 'Pre-Departure', description: 'Accommodation, flight booking, BRP collection guidance, and arrival support.' },
    ],
    costTable: [
      { item: 'Minimum Tuition/yr', foreign: 'GBP 10,000', naira: naira(10000, 'GBP') },
      { item: 'Maximum Tuition/yr', foreign: 'GBP 38,000', naira: naira(38000, 'GBP') },
      { item: 'Living Expenses/yr', foreign: 'GBP 12,000–15,000', naira: nairaRange(12000, 15000, 'GBP') },
      { item: 'NHS Surcharge/yr', foreign: 'GBP 776', naira: naira(776, 'GBP') },
      { item: 'Total Estimated/yr', foreign: 'GBP 22,776–53,776', naira: nairaRange(22776, 53776, 'GBP') },
    ],
    healthInsurance: { foreign: 'GBP 776/yr (NHS surcharge)', naira: naira(776, 'GBP') },
    quizQuestions: [
      { question: 'Do you want to complete your degree in the shortest time?', options: ['Yes, 1 year is ideal', 'I prefer 2 years', 'Duration doesn\'t matter', 'Not sure'] },
      { question: 'What is your annual budget?', options: ['Under ₦30M', '₦30M–₦50M', '₦50M–₦80M', 'Over ₦80M'] },
      { question: 'What is your IELTS score?', options: ['Below 6.0', '6.0–6.5', '6.5–7.0', '7.0+'] },
      { question: 'Are you interested in staying after studies?', options: ['Yes, 2yr Graduate Visa', 'Maybe', 'Just the degree', 'Not sure'] },
      { question: 'What level of study?', options: ['Undergraduate', 'Master\'s', 'PhD', 'Foundation'] },
    ],
    faqs: [
      { question: 'What is a CAS letter and how do I get one?', answer: 'A CAS (Confirmation of Acceptance for Studies) is a unique reference number issued by your UK university after you accept an offer and pay a deposit. You need it for your visa application. The university issues it electronically.' },
      { question: 'What financial evidence do I need for a UK student visa?', answer: 'You must show tuition fees (minus any deposits paid) plus living costs of £1,334/month for up to 9 months (outside London) or £1,023/month (inside London). Funds must be held for at least 28 consecutive days.' },
      { question: 'How does the 2yr Graduate Visa work?', answer: 'After completing your UK degree, you can apply for a 2-year Graduate Visa (3 years for PhD graduates). It allows you to work in any role without employer sponsorship.' },
      { question: 'How much is the NHS surcharge?', answer: 'The Immigration Health Surcharge is currently £776 per year for students. This gives you access to the National Health Service (NHS) during your stay.' },
      { question: 'Where do I do biometrics in Nigeria?', answer: 'Biometrics for UK visa applications are collected at TLScontact centres in Lagos, Abuja, and other locations. You\'ll book an appointment after submitting your online application.' },
      { question: 'How long does a UK student visa take from Nigeria?', answer: 'Processing typically takes approximately 3 weeks from your biometrics appointment. Priority processing (5 working days) is available for an additional fee.' },
    ],
    relatedDestinations: ['canada', 'ireland'],
  },

  usa: {
    slug: 'usa',
    name: 'USA',
    flag: '🇺🇸',
    gradient: 'linear-gradient(135deg, #002868, #3C3B6E, #BF0A30)',
    accent: '#002868',
    keyStat: '12–36mo OPT',
    visaSuccess: '96%',
    tuition: { min: 20000, max: 55000, currency: 'USD' },
    living: { min: 15000, max: 25000, currency: 'USD' },
    workRights: 'On-campus 20hrs/wk only',
    postStudy: '12–36mo OPT (STEM: 36mo)',
    visaProcessing: '2–3 months',
    community: 'Large — Over 300,000 Nigerians in the USA, second largest African immigrant group. Strong Nigerian student associations at most major universities.',
    communitySize: 'Large',
    prPathway: 'No (complex)',
    h1: 'Study in the USA from Nigeria',
    metaTitle: 'Study in the USA from Nigeria 2025 | The Study Abroad Consultant',
    metaDescription: 'Expert guidance for Nigerian students applying to US universities. 96% visa success rate. Full Naira cost breakdown. Free consultation.',
    whyChoose: [
      { icon: 'Trophy', title: 'Top-Ranked Universities', description: 'The US has more top-100 universities than any other country, offering unmatched academic prestige.' },
      { icon: 'Lightbulb', title: 'Research Opportunities', description: 'Access to world-leading research facilities, labs, and innovation ecosystems.' },
      { icon: 'Briefcase', title: 'OPT Work Rights', description: '12 months of Optional Practical Training after graduation — 36 months for STEM graduates.' },
      { icon: 'BookOpen', title: 'Flexible Curricula', description: 'Choose your major after enrolment, take electives across disciplines, and customise your degree.' },
      { icon: 'DollarSign', title: 'Scholarship Opportunities', description: 'Generous merit and need-based scholarships available at many institutions.' },
      { icon: 'Users', title: 'Nigerian Community', description: 'Over 300,000 Nigerians in the US with strong student associations and alumni networks.' },
    ],
    communityFacts: [
      'Second largest African immigrant group in the US',
      'Active Nigerian student associations at most universities',
      'Strong alumni networks in tech, finance, and healthcare',
    ],
    timeline: [
      { week: 'Week 1', title: 'Initial Consultation', description: 'Free assessment of your profile and US university options.' },
      { week: 'Weeks 2–4', title: 'Test Prep & Documents', description: 'SAT/GRE/GMAT preparation guidance and document gathering.' },
      { week: 'Weeks 4–8', title: 'University Applications', description: 'Application submission to chosen universities with essays and recommendation letters.' },
      { week: 'Weeks 8–14', title: 'Offer & I-20 Form', description: 'Accept your offer, receive your I-20 form from the university.' },
      { week: 'Weeks 14–16', title: 'SEVIS Fee & DS-160', description: 'Pay the SEVIS fee ($350), complete DS-160 online form, and book embassy interview.', callout: 'SEVIS fee of $350 (≈₦560,000) must be paid before your visa interview.' },
      { week: 'Weeks 16–18', title: 'F-1 Visa Interview', description: 'In-person interview at the US Embassy in Lagos or Consulate in Abuja. We provide full mock interview prep.', callout: 'The visa interview is the most critical step — preparation is essential.' },
      { week: 'Weeks 18–24', title: 'Visa Decision & Travel', description: 'Visa processing takes 2–3 months. Pre-departure planning and arrival support.' },
    ],
    costTable: [
      { item: 'Minimum Tuition/yr', foreign: 'USD 20,000', naira: naira(20000, 'USD') },
      { item: 'Maximum Tuition/yr', foreign: 'USD 55,000', naira: naira(55000, 'USD') },
      { item: 'Living Expenses/yr', foreign: 'USD 15,000–25,000', naira: nairaRange(15000, 25000, 'USD') },
      { item: 'Health Insurance/yr', foreign: 'USD 1,500–3,000', naira: nairaRange(1500, 3000, 'USD') },
      { item: 'Total Estimated/yr', foreign: 'USD 36,500–83,000', naira: nairaRange(36500, 83000, 'USD') },
    ],
    healthInsurance: { foreign: 'USD 1,500–3,000/yr', naira: nairaRange(1500, 3000, 'USD') },
    quizQuestions: [
      { question: 'Are you interested in STEM programs?', options: ['Yes', 'Maybe', 'No', 'Not sure'] },
      { question: 'What is your annual budget?', options: ['Under ₦40M', '₦40M–₦70M', '₦70M–₦100M', 'Over ₦100M'] },
      { question: 'Do you have SAT/GRE/GMAT scores?', options: ['Yes, strong scores', 'Yes, average', 'Not yet', 'Not required'] },
      { question: 'Are you comfortable with a visa interview?', options: ['Yes', 'Nervous but willing', 'Need coaching', 'Very nervous'] },
      { question: 'What level of study?', options: ['Undergraduate', 'Master\'s', 'PhD', 'Certificate'] },
    ],
    faqs: [
      { question: 'What tips do you have for the F-1 visa interview in Nigeria?', answer: 'Be concise and confident. Clearly explain your study plans, how you\'ll fund your education, and your ties to Nigeria. Avoid memorised answers. We provide full mock interview sessions specific to the Lagos and Abuja embassies.' },
      { question: 'What is the difference between OPT and CPT?', answer: 'CPT (Curricular Practical Training) allows work during your studies as part of your curriculum. OPT (Optional Practical Training) is post-graduation work authorization — 12 months standard, or 36 months for STEM graduates.' },
      { question: 'How much is the SEVIS fee?', answer: 'The SEVIS I-901 fee is $350 (≈₦560,000) for F-1 students. It must be paid before your visa interview and is non-refundable.' },
      { question: 'Can I work while studying in the US?', answer: 'F-1 students can work on-campus for up to 20 hours per week during the semester. Off-campus employment is only allowed through CPT or in cases of severe economic hardship.' },
      { question: 'What financial documentation do I need?', answer: 'You need bank statements showing sufficient funds for at least the first year of study, plus a sponsor letter if applicable. All documents should show amounts in USD equivalent.' },
      { question: 'Is it harder to get a US student visa from Nigeria?', answer: 'The US visa process involves an interview, which some find challenging. However, with proper documentation and interview preparation, our students achieve a 96% success rate.' },
    ],
    relatedDestinations: ['canada', 'uk'],
  },

  ireland: {
    slug: 'ireland',
    name: 'Ireland',
    flag: '🇮🇪',
    gradient: 'linear-gradient(135deg, #169B62, #1a7a4a, #0d5c35)',
    accent: '#169B62',
    keyStat: 'EU Access · English-Speaking',
    visaSuccess: '97%',
    tuition: { min: 9000, max: 25000, currency: 'EUR' },
    living: { min: 10000, max: 12000, currency: 'EUR' },
    workRights: '20hrs term, full-time holidays',
    postStudy: '1–2yr Stay Back / Graduate Permission',
    visaProcessing: '4–6 weeks',
    community: 'Growing — A vibrant and growing Nigerian community in Dublin and Limerick, with strong Pentecostal church networks that many Nigerian students already feel connected to before arrival.',
    communitySize: 'Growing',
    prPathway: 'Possible (Stamp 4)',
    h1: 'Study in Ireland from Nigeria',
    metaTitle: 'Study in Ireland from Nigeria 2025 | The Study Abroad Consultant',
    metaDescription: 'Expert guidance for Nigerian students applying to Irish universities. 97% visa success rate. Full Naira cost breakdown. Free consultation.',
    whyChoose: [
      { icon: 'Globe', title: 'EU Access', description: 'An English-speaking gateway to the European Union job market and travel opportunities.' },
      { icon: 'DollarSign', title: 'Affordable Tuition', description: 'Lower tuition than UK or USA, with quality institutions and strong graduate outcomes.' },
      { icon: 'Briefcase', title: 'Stay Back Visa', description: '1–2 year Graduate Permission to work in Ireland after completing your degree.' },
      { icon: 'Building', title: 'Tech Hub of Europe', description: 'Home to European HQs of Google, Meta, Apple, and hundreds of tech companies.' },
      { icon: 'Heart', title: 'Welcoming Culture', description: 'Consistently ranked among the friendliest countries for international students.' },
      { icon: 'Users', title: 'Growing Nigerian Community', description: 'A vibrant and growing Nigerian community in Dublin, Limerick, and other cities.' },
    ],
    communityFacts: [
      'Vibrant Nigerian community in Dublin and Limerick',
      'Strong Pentecostal church networks',
      'Growing Nigerian professional associations',
    ],
    timeline: [
      { week: 'Week 1', title: 'Initial Consultation', description: 'Free assessment of your profile and Irish university options.' },
      { week: 'Weeks 2–4', title: 'University Shortlisting', description: 'Matched to 3–5 Irish institutions based on your profile and budget.' },
      { week: 'Weeks 4–8', title: 'Application & Documents', description: 'Application submission with personal statement and supporting documents.' },
      { week: 'Weeks 8–12', title: 'Offer & Acceptance', description: 'Accept your offer and pay the required deposit.' },
      { week: 'Weeks 12–16', title: 'Visa Application', description: 'Irish student visa application with financial evidence and medical insurance proof.' },
      { week: 'Weeks 16–20', title: 'Visa Decision & Travel', description: 'Processing takes 4–6 weeks. GNIB/IRP registration arranged for after arrival.' },
    ],
    costTable: [
      { item: 'Minimum Tuition/yr', foreign: 'EUR 9,000', naira: naira(9000, 'EUR') },
      { item: 'Maximum Tuition/yr', foreign: 'EUR 25,000', naira: naira(25000, 'EUR') },
      { item: 'Living Expenses/yr', foreign: 'EUR 10,000–12,000', naira: nairaRange(10000, 12000, 'EUR') },
      { item: 'Health Insurance/yr', foreign: 'EUR 500–800', naira: nairaRange(500, 800, 'EUR') },
      { item: 'Total Estimated/yr', foreign: 'EUR 19,500–37,800', naira: nairaRange(19500, 37800, 'EUR') },
    ],
    healthInsurance: { foreign: 'EUR 500–800/yr', naira: nairaRange(500, 800, 'EUR') },
    quizQuestions: [
      { question: 'Are you interested in working in EU tech companies?', options: ['Yes', 'Maybe', 'No', 'Not sure'] },
      { question: 'What is your annual budget?', options: ['Under ₦25M', '₦25M–₦40M', '₦40M–₦55M', 'Over ₦55M'] },
      { question: 'Is English your preferred language of instruction?', options: ['Yes', 'Open to others', 'Not sure'] },
      { question: 'Do you want a pathway to EU residency?', options: ['Yes', 'Maybe', 'Not a priority', 'Not sure'] },
      { question: 'What level of study?', options: ['Undergraduate', 'Master\'s', 'PhD', 'Certificate'] },
    ],
    faqs: [
      { question: 'What is GNIB/IRP registration?', answer: 'After arriving in Ireland, you must register with the Garda National Immigration Bureau (GNIB) or Irish Residence Permit (IRP) office within 90 days. This gives you your residence permit card (Stamp 2 for students).' },
      { question: 'What is Stamp 2 in Ireland?', answer: 'Stamp 2 is the immigration permission for international students in Ireland. It allows you to study full-time and work up to 20 hours per week during term time and 40 hours during holidays.' },
      { question: 'How do part-time work limits work in Ireland?', answer: 'During term: 20 hours per week. During holidays (June–September and December 15–January 15): 40 hours per week. The minimum wage in Ireland is €12.70/hr.' },
      { question: 'How does Irish healthcare work for students?', answer: 'International students must have private health insurance. Some universities offer group schemes. Public emergency care is available, but you should have comprehensive cover for the duration of your studies.' },
      { question: 'What is the Stay Back Visa (Graduate Permission)?', answer: 'The Graduate Permission allows you to remain in Ireland after graduation to seek employment. Master\'s graduates get 2 years; Bachelor\'s graduates get 1 year. If you find a qualifying job, you can transition to a Stamp 1 work permit.' },
      { question: 'Can I get permanent residency in Ireland?', answer: 'Yes, through the Stamp 4 pathway. After 5 years of legal residence (including time on Stamp 2 and Stamp 1), you may be eligible for long-term residency or citizenship.' },
    ],
    relatedDestinations: ['uk', 'germany'],
  },

  germany: {
    slug: 'germany',
    name: 'Germany',
    flag: '🇩🇪',
    gradient: 'linear-gradient(135deg, #1a1a1a, #2d2d2d, #D4A017)',
    accent: '#D4A017',
    keyStat: 'Near-Zero Tuition Available',
    visaSuccess: '94%',
    tuition: { min: 0, max: 20000, currency: 'EUR', note: 'Public universities: FREE (only semester fee of €150–350)' },
    living: { min: 10000, max: 12000, currency: 'EUR' },
    workRights: '20hrs/wk during term',
    postStudy: '18mo job-seeker visa',
    visaProcessing: '6–8 weeks',
    community: 'Smaller — A growing Nigerian community in Frankfurt, Munich, and Berlin, with increasing connections through international student groups and African diaspora networks.',
    communitySize: 'Smaller',
    prPathway: 'Yes (5yr residence)',
    h1: 'Study in Germany from Nigeria for Free: Tuition Costs, Visa & Universities (2025)',
    metaTitle: 'Study in Germany from Nigeria for Free 2025 | The Study Abroad Consultant',
    metaDescription: 'Nigerian students can study in Germany for free at public universities. 94% visa success rate. Blocked account guide. Full Naira cost breakdown.',
    whyChoose: [
      { icon: 'DollarSign', title: 'Near-Zero Tuition', description: 'Most German public universities charge NO tuition fees — only a semester fee of €150–350 (≈₦262,500–₦612,500).' },
      { icon: 'Award', title: 'World-Class Engineering', description: 'Germany is globally renowned for engineering, technology, and science programs.' },
      { icon: 'TrendingUp', title: 'Strong Economy', description: 'Europe\'s largest economy with a strong job market for skilled graduates.' },
      { icon: 'Briefcase', title: '18mo Job-Seeker Visa', description: 'After graduation, stay for 18 months to find a job related to your field of study.' },
      { icon: 'Globe', title: 'EU Access', description: 'Live and travel freely across the Schengen zone during your studies.' },
      { icon: 'BookOpen', title: 'English-Taught Programs', description: 'Hundreds of Master\'s programs taught entirely in English — no German required.' },
    ],
    communityFacts: [
      'Growing Nigerian community in Frankfurt, Munich, Berlin',
      'International student groups at every university',
      'African diaspora cultural networks',
    ],
    timeline: [
      { week: 'Week 1', title: 'Initial Consultation', description: 'Free assessment of your profile and German university options.' },
      { week: 'Weeks 2–6', title: 'University Research & Application', description: 'Identify programs, check requirements, and prepare application documents.' },
      { week: 'Weeks 6–10', title: 'Application Submission', description: 'Submit applications via uni-assist or directly to universities.' },
      { week: 'Weeks 10–14', title: 'Admission & Blocked Account', description: 'Accept your offer and open a blocked account (€11,904 minimum).', callout: 'Blocked account requires €11,904 (≈₦20.8M). Opening takes 3–4 weeks via Fintiba or Expatrio.' },
      { week: 'Weeks 14–18', title: 'Visa Application', description: 'Apply at the German Embassy in Lagos or Abuja with blocked account confirmation, admission letter, and health insurance.' },
      { week: 'Weeks 18–24', title: 'Visa Decision', description: 'Processing takes 6–8 weeks. German student visa requires more documentation than many countries.', callout: 'Unlike India/China, Nigerian students do NOT need an APS certificate.' },
      { week: 'Weeks 24–26', title: 'Pre-Departure & Arrival', description: 'Accommodation, city registration (Anmeldung), and orientation support.' },
    ],
    costTable: [
      { item: 'Tuition (Public University)', foreign: 'EUR 0 (Free)', naira: '₦0 (Free)' },
      { item: 'Semester Fee', foreign: 'EUR 150–350/semester', naira: nairaRange(150, 350, 'EUR') },
      { item: 'Tuition (Private University)', foreign: 'EUR 5,000–20,000/yr', naira: nairaRange(5000, 20000, 'EUR') },
      { item: 'Living Expenses/yr', foreign: 'EUR 10,000–12,000', naira: nairaRange(10000, 12000, 'EUR') },
      { item: 'Health Insurance/yr', foreign: 'EUR 1,200', naira: naira(1200, 'EUR') },
      { item: 'Blocked Account (one-time)', foreign: 'EUR 11,904', naira: naira(11904, 'EUR') },
    ],
    healthInsurance: { foreign: 'EUR 1,200/yr', naira: naira(1200, 'EUR') },
    quizQuestions: [
      { question: 'Is low/no tuition your top priority?', options: ['Yes, definitely', 'Important but not only factor', 'Not a priority', 'Not sure'] },
      { question: 'Can you fund the blocked account (≈₦20.8M)?', options: ['Yes', 'With some effort', 'Would need help', 'Not sure'] },
      { question: 'Are you interested in engineering/STEM?', options: ['Yes', 'Maybe', 'No, different field', 'Not sure'] },
      { question: 'Are you open to learning German?', options: ['Yes, excited', 'If needed', 'Prefer English only', 'Already speak some'] },
      { question: 'What level of study?', options: ['Bachelor\'s', 'Master\'s', 'PhD', 'Studienkolleg'] },
    ],
    faqs: [
      { question: 'Do Nigerian students need an APS certificate for Germany?', answer: 'No — unlike India and China, Nigerian students do NOT currently require an APS (Academic Evaluation Centre) certificate to apply to German universities. This is commonly misunderstood. Nigerian students apply directly with their original academic documents, duly authenticated.' },
      { question: 'What is a blocked account and how much does it cost?', answer: 'A blocked account (Sperrkonto) is a special bank account that proves you can financially support yourself in Germany. The minimum amount is €11,904 (≈₦20.8M). You can release about €992/month for living expenses. Providers include Fintiba and Expatrio.' },
      { question: 'Do I need to speak German to study in Germany?', answer: 'Not necessarily. There are hundreds of Master\'s programs taught entirely in English. However, Bachelor\'s programs typically require German (TestDaF or DSH). Basic German helps with daily life regardless of your program language.' },
      { question: 'What is Studienkolleg?', answer: 'Studienkolleg is a preparatory course for international students whose school-leaving certificates are not directly recognised in Germany. It typically lasts 1 year and prepares you for university-level study. Nigerian WAEC holders may need this for some programs.' },
      { question: 'How does the 18-month job-seeker visa work?', answer: 'After graduating from a German university, you can apply for an 18-month residence permit to find a job related to your field of study. Once employed, this converts to a work visa. After 5 years of residence, you can apply for permanent residency.' },
      { question: 'Are Nigerian degrees recognised in Germany?', answer: 'German universities evaluate Nigerian qualifications on a case-by-case basis. A Bachelor\'s degree from a recognised Nigerian university is generally accepted for Master\'s programs. For direct Bachelor\'s admission, additional assessment may be required.' },
    ],
    relatedDestinations: ['ireland', 'canada'],
  },

  australia: {
    slug: 'australia',
    name: 'Australia',
    flag: '🇦🇺',
    gradient: 'linear-gradient(135deg, #00843D, #2d7a3e, #FFCD00)',
    accent: '#FFCD00',
    keyStat: 'Unlimited Work Rights',
    visaSuccess: '96%',
    tuition: { min: 20000, max: 45000, currency: 'AUD' },
    living: { min: 21000, max: 27000, currency: 'AUD' },
    workRights: '48hrs/fortnight (unlimited since July 2023)',
    postStudy: '2–4yr Subclass 485',
    visaProcessing: '4–6 weeks',
    community: 'Growing — A fast-growing Nigerian community in Sydney, Melbourne, and Brisbane, with active Nigerian professional associations and church communities.',
    communitySize: 'Growing',
    prPathway: 'Yes (skilled migration)',
    h1: 'Study in Australia from Nigeria',
    metaTitle: 'Study in Australia from Nigeria 2025 | The Study Abroad Consultant',
    metaDescription: 'Expert guidance for Nigerian students applying to Australian universities. 96% visa success rate. Full Naira cost breakdown. Free consultation.',
    whyChoose: [
      { icon: 'Briefcase', title: 'Best Work Rights', description: 'Work up to 48 hours per fortnight during studies — the most generous work rights of any major destination.' },
      { icon: 'TrendingUp', title: 'PR Pathway', description: 'Skilled migration pathway through the points-based system after graduation.' },
      { icon: 'Award', title: 'Top Universities', description: '7 of the world\'s top 100 universities, with globally recognised degrees.' },
      { icon: 'Sun', title: 'Quality of Life', description: 'Consistently ranked among the world\'s most liveable countries with excellent healthcare and safety.' },
      { icon: 'DollarSign', title: 'High Earning Potential', description: 'Australia has one of the highest minimum wages in the world — AUD 23.23/hr.' },
      { icon: 'Users', title: 'Growing Nigerian Community', description: 'Fast-growing Nigerian community in Sydney, Melbourne, and Brisbane with professional associations.' },
    ],
    communityFacts: [
      'Fast-growing Nigerian community in major cities',
      'Active Nigerian professional associations',
      'Nigerian church communities in Sydney, Melbourne, Brisbane',
    ],
    timeline: [
      { week: 'Week 1', title: 'Initial Consultation', description: 'Free assessment of your profile and Australian university options.' },
      { week: 'Weeks 2–4', title: 'University Shortlisting', description: 'Matched to 3–5 Australian universities based on your goals and budget.' },
      { week: 'Weeks 4–8', title: 'Application & GTE Statement', description: 'Application submission with Genuine Temporary Entrant (GTE) statement — a critical document.', callout: 'The GTE statement is crucial for Australian student visas. We help you write a compelling one.' },
      { week: 'Weeks 8–12', title: 'Offer & Acceptance', description: 'Accept your offer, arrange OSHC health insurance, and receive your Confirmation of Enrolment (CoE).' },
      { week: 'Weeks 12–16', title: 'Visa Application (Subclass 500)', description: 'Online visa application with CoE, financial evidence, GTE statement, and OSHC.' },
      { week: 'Weeks 16–22', title: 'Visa Decision & Travel', description: 'Processing takes 4–6 weeks. Pre-departure orientation and arrival support.' },
    ],
    costTable: [
      { item: 'Minimum Tuition/yr', foreign: 'AUD 20,000', naira: naira(20000, 'AUD') },
      { item: 'Maximum Tuition/yr', foreign: 'AUD 45,000', naira: naira(45000, 'AUD') },
      { item: 'Living Expenses/yr', foreign: 'AUD 21,000–27,000', naira: nairaRange(21000, 27000, 'AUD') },
      { item: 'OSHC Insurance/yr', foreign: 'AUD 600', naira: naira(600, 'AUD') },
      { item: 'Total Estimated/yr', foreign: 'AUD 41,600–72,600', naira: nairaRange(41600, 72600, 'AUD') },
    ],
    healthInsurance: { foreign: 'AUD 600/yr (OSHC)', naira: naira(600, 'AUD') },
    quizQuestions: [
      { question: 'Is work flexibility during studies important to you?', options: ['Very important', 'Somewhat', 'Not a priority', 'Not sure'] },
      { question: 'What is your annual budget?', options: ['Under ₦30M', '₦30M–₦50M', '₦50M–₦70M', 'Over ₦70M'] },
      { question: 'Are you interested in skilled migration after studies?', options: ['Yes', 'Maybe', 'Just the degree', 'Not sure'] },
      { question: 'Do you prefer a warm climate?', options: ['Yes', 'Don\'t mind', 'Prefer cooler', 'No preference'] },
      { question: 'What level of study?', options: ['Undergraduate', 'Master\'s', 'PhD', 'Vocational/TAFE'] },
    ],
    faqs: [
      { question: 'What is the GTE statement and what should I write?', answer: 'The Genuine Temporary Entrant (GTE) statement explains why you want to study in Australia, why you chose your course and institution, and how it relates to your career plans back home. Be specific about your goals and honest about your circumstances. Avoid generic statements.' },
      { question: 'How much does OSHC health insurance cost?', answer: 'Overseas Student Health Cover (OSHC) costs approximately AUD 600/year (≈₦630,000). It is mandatory for the duration of your student visa and must be arranged before your visa application.' },
      { question: 'What are the Subclass 500 visa requirements?', answer: 'You need a Confirmation of Enrolment (CoE), valid OSHC, a Genuine Temporary Entrant (GTE) statement, proof of financial capacity, English language test results, and a valid passport.' },
      { question: 'How do I show financial capacity from Nigeria?', answer: 'You need to demonstrate access to funds covering tuition + AUD 21,041/yr for living costs. This can be shown through bank statements, loan approval letters, or scholarship letters. All documents must be translated to English if not already.' },
      { question: 'What is the Subclass 485 visa?', answer: 'The Temporary Graduate visa (Subclass 485) allows you to work in Australia after graduation. Duration depends on your qualification: 2 years for Bachelor\'s/Master\'s coursework, 3 years for Master\'s by research, 4 years for PhD. Regional study can add extra years.' },
      { question: 'Why are Australian work rights the most generous?', answer: 'Since July 2023, international students in Australia can work up to 48 hours per fortnight (effectively 24hrs/wk) with no restrictions during holidays. Combined with Australia\'s high minimum wage (AUD 23.23/hr), this makes Australia the best destination for students who want to work and study.' },
    ],
    relatedDestinations: ['canada', 'uk'],
  },
}

export function getDestination(slug: string): Destination | undefined {
  return destinations[slug]
}

export function getAllDestinations(): Destination[] {
  return Object.values(destinations)
}

export function getDestinationSlugs(): string[] {
  return Object.keys(destinations)
}
